[build]
  functions = "."  # Current directory (coinbackend)
  # REMOVE the publish line completely since you don't have a frontend

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index/api/health"
  status = 200

# Add this to handle any other paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200