[build]
  functions = "coinbackend"
  publish = "."  # Force current directory

# Disable build processing completely
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index/api/health"
  status = 200

# Add this to handle any caching issues
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"