[build]
  functions = "."  # Point to root directory where index.js is located

[functions]
  external_node_modules = ["express", "mongoose", "bcryptjs", "jsonwebtoken", "cors", "dotenv", "firebase-admin", "multer", "node-fetch", "indexless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"  # Point to index.js
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/index/:splat"  # Point to index.js
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"  # Redirect root to index.js
  status = 200