[build]
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

# Remove the external_node_modules from functions section
# and use node_bundle with the correct syntax

[functions]
  # Correct node_bundle syntax
  [functions.node_bundle]
    external_node_modules = ["mongoose", "mongodb", "express", "cors", "dotenv", "@supabase/supabase-js", "node-fetch", "serverless-http"]

# Redirect all API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For SPA routing - redirect all non-API requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle preflight requests for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"