[build]
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/./functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/./functions/api/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/health/"
  to = "/.netlify/functions/api/health"
  status = 200
  force = true