[build]
  functions = "coinbackend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

# Health check endpoint at root
[[redirects]]
  from = "/"
  to = "/.netlify/functions/index/api/health"
  status = 200

# Test endpoint
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/index/test"
  status = 200