[build]
  functions = "functions"
  # Remove the publish line since you don't have a public directory
  # publish = "public"

[build.environment]
  NODE_VERSION = "18"
  APP_BASE_URL = "https://coinwavezbackend.netlify.app"
  VITE_SUPABASE_URL = "https://cgyjbbuwiykxmsirigsp.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneWpiYnV3aXlreG1zaXJpZ3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODc4NjksImV4cCI6MjA3MzM2Mzg2OX0.bbaW1VutO8acWD0n_m_yWaH0zkVS8w0iBXA5otYbxqM"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Remove the frontend redirect since you don't have a frontend
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  node_bundler = "esbuild"