[build]
  functions = "coinbackend"
  publish = "."  # Force current directory

# Explicitly tell Netlify to skip build processing
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index/api/health"
  status = 200

# Add headers to prevent caching issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Netlify-Functions = "enabled"