[build]
  functions = "coinbackend"
  # Remove or comment out the publish line since you don't have a frontend
  # publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

# Add a simple redirect for the root path
[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200